petl:
  homeDir: "/home/petl"
  datasourceDir: "${petl.homeDir}/datasources"
  jobDir: "${petl.homeDir}/jobs"
  startup:
    jobs:
      - "refresh-full.yml"
    exitAutomatically: true

server:
  port: 9109

logging:
  level:
    root: "WARN"
    org.pih: "DEBUG"

rwinkwavuOpenmrs:
  host: "localhost"
  port: "3306"
  databaseName: "rwinkwavu"
  user: "root"
  password: "password"

butaroOpenmrs:
  host: "localhost"
  port: "3306"
  databaseName: "butaro"
  user: "root"
  password: "root"

kireheOpenmrs:
  host: "localhost"
  port: "3306"
  databaseName: "kirehe"
  user: "root"
  password: "root"

reporting:
  host: "localhost"
  port: "3306"
  databaseName: "reporting"
  user: "root"
  password: "root"

anonymized:
  host: "localhost"
  port: "3306"
  databaseName: "anonymized"
  user: "root"
  password: "root"