select   
	enc.patient_id as patient_id,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @SERUM_GLUCOSE limit 1) as SERUM_GLUCOSE,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @SERUM_CREATININE limit 1) as SERUM_CREATININE,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Glucose_Test limit 1) as Glucose_Test,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @PULSE limit 1) as PULSE,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Compliance limit 1) as Compliance,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @HYPOGLYCEMIA limit 1) as HYPOGLYCEMIA,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @WEIGHT_KG limit 1) as WEIGHT_KG,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @HbA1c limit 1) as HbA1c,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @URINARY_ALBUMIN limit 1) as URINARY_ALBUMIN,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @DIASTOLIC_BLOOD_PRESSURE limit 1) as DIASTOLIC_BLOOD_PRESSURE,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @SYSTOLIC_BLOOD_PRESSURE limit 1) as SYSTOLIC_BLOOD_PRESSURE,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Sensation_in_right_foot limit 1) as Sensation_in_right_foot,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Sensation_in_left_foot limit 1) as Sensation_in_left_foot,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @RETURN_VISIT_DATE limit 1) as RETURN_VISIT_DATE,
	(select value_datetime from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @EXTREMITY_EXAM_FINDINGS limit 1) as EXTREMITY_EXAM_FINDINGS,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @HEIGHT_CM limit 1) as HEIGHT_CM,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Physical_pain_score limit 1) as Physical_pain_score,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Psychological_pain_score limit 1) as Psychological_pain_score,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Spiritual_pain_score limit 1) as Spiritual_pain_score,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Pain_score_comments limit 1) as Pain_score_comments,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @COMMENTS_AT_CONCLUSION_OF_EXAMINATION limit 1) as COMMENTS_AT_CONCLUSION_OF_EXAMINATION,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Part_of_the_day limit 1) as Part_of_the_day,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @CREATININE_CLEARANCE limit 1) as CREATININE_CLEARANCE,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @SERUM_SODIUM limit 1) as SERUM_SODIUM,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @SERUM_POTASSIUM limit 1) as SERUM_POTASSIUM,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @BODY_MASS_INDEX_MEASURED limit 1) as BODY_MASS_INDEX_MEASURED,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @OPHTHALMOLOGY_SERVICE limit 1) as OPHTHALMOLOGY_SERVICE,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @MORNING_DOSE_IN_MILLIGRAMS limit 1) as MORNING_DOSE_IN_MILLIGRAMS,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @NIGHT_DOSE_IN_MILLIGRAMS limit 1) as NIGHT_DOSE_IN_MILLIGRAMS,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @BED_TIME_DOSE_IN_MILLIGRAMS limit 1) as BED_TIME_DOSE_IN_MILLIGRAMS,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Diagnosis_or_problem_non_coded limit 1) as Diagnosis_or_problem_non_coded,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Pain_drugs limit 1) as Pain_drugs,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @other_pain_drugs limit 1) as other_pain_drugs,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @NOON_DOSE_IN_MILLIGRAMS limit 1) as NOON_DOSE_IN_MILLIGRAMS,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @OTHER_LAB_TEST_NAME limit 1) as OTHER_LAB_TEST_NAME,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @OTHER_LAB_TEST_RESULT limit 1) as OTHER_LAB_TEST_RESULT,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @ABDOMINAL_EXAM_FINDINGS limit 1) as ABDOMINAL_EXAM_FINDINGS,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @CURRENT_COMPLAINTS_OR_SYMPTOMS limit 1) as CURRENT_COMPLAINTS_OR_SYMPTOMS,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Surgical_history limit 1) as Surgical_history,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @MEDICATION_HISTORY limit 1) as MEDICATION_HISTORY,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @ALLERGIC limit 1) as ALLERGIC,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @TYPE_OF_REFERRING_CLINIC_OR_HOSPITAL limit 1) as TYPE_OF_REFERRING_CLINIC_OR_HOSPITAL,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @NAME_OF_REFERRING_SITE limit 1) as NAME_OF_REFERRING_SITE,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @UROGENITAL_EXAM_FINDINGS limit 1) as UROGENITAL_EXAM_FINDINGS,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Type_of_diabetes_diagnosis limit 1) as Type_of_diabetes_diagnosis,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @LUNG_EXAM_FINDINGS limit 1) as LUNG_EXAM_FINDINGS,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @RESPIRATORY_RATE limit 1) as RESPIRATORY_RATE,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @CHRONIC_CARE_DIAGNOSIS limit 1) as CHRONIC_CARE_DIAGNOSIS,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @GENERAL_EXAM_FINDINGS limit 1) as GENERAL_EXAM_FINDINGS,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @BLOOD_OXYGEN_SATURATION limit 1) as BLOOD_OXYGEN_SATURATION,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Chest_Thorax_Exam_Findings limit 1) as Chest_Thorax_Exam_Findings,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @UBUDEHE_CATEGORY limit 1) as UBUDEHE_CATEGORY,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @PATIENTS_FLUID_MANAGEMENT limit 1) as PATIENTS_FLUID_MANAGEMENT,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @HEENT_EXAM_FINDINGS limit 1) as HEENT_EXAM_FINDINGS,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @CARDIAC_MEDICATION limit 1) as CARDIAC_MEDICATION,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @CARDIAC_EXAM_FINDINGS limit 1) as CARDIAC_EXAM_FINDINGS,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @NEUROLOGICAL_EXAM_FINDINGS limit 1) as NEUROLOGICAL_EXAM_FINDINGS,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @TEMPERATURE_C limit 1) as TEMPERATURE_C,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Clinican_notes limit 1) as Clinican_notes,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Obstestrical limit 1) as Obstestrical,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @HEMATOCRIT limit 1) as HEMATOCRIT,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @ASAT_RESULT limit 1) as ASAT_RESULT,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @RESULT_OF_HIV_TEST limit 1) as RESULT_OF_HIV_TEST,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @MONOCYTES limit 1) as MONOCYTES,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @TIME_UNITS limit 1) as TIME_UNITS,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Morning_Dose_in_Units limit 1) as Morning_Dose_in_Units,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Diabetes_Medications limit 1) as Diabetes_Medications,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Evening_Dose_in_Units limit 1) as Evening_Dose_in_Units,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Noon_Dose_in_Units limit 1) as Noon_Dose_in_Units,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @PLATELETS limit 1) as PLATELETS,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @LYMPHOCYTES limit 1) as LYMPHOCYTES,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @NEUTROPHILS limit 1) as NEUTROPHILS,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Bedtime_Dose_in_Units limit 1) as Bedtime_Dose_in_Units,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @RED_BLOOD_CELLS limit 1) as RED_BLOOD_CELLS,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @WHITE_BLOOD_CELLS limit 1) as WHITE_BLOOD_CELLS,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @BLOOD_UREA_NITROGEN limit 1) as BLOOD_UREA_NITROGEN,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @ALAT_RESULT limit 1) as ALAT_RESULT,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Patient_Medical_History limit 1) as Patient_Medical_History,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @EOSINOPHILS limit 1) as EOSINOPHILS,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Duration limit 1) as Duration,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @HEMOGLOBIN limit 1) as HEMOGLOBIN,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Other limit 1) as Other,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @patient_chronic_disease_history limit 1) as patient_chronic_disease_history,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @TELEPHONE_NUMBER limit 1) as TELEPHONE_NUMBER,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Patients_Contact_Phone_Owner limit 1) as Patients_Contact_Phone_Owner,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Family_Care_giver_Phone_Number limit 1) as Family_Care_giver_Phone_Number,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @NAME_OF_HEALTH_CARE_PROVIDER limit 1) as NAME_OF_HEALTH_CARE_PROVIDER,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @PREVIOUS_MEDICAL_HISTORY limit 1) as PREVIOUS_MEDICAL_HISTORY,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @DDB_ECHOCARDIOGRAPH_RESULT limit 1) as DDB_ECHOCARDIOGRAPH_RESULT,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @treatment_appoach limit 1) as treatment_appoach,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Family_Care_giver_name limit 1) as Family_Care_giver_name,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @TOTAL_PROTEIN limit 1) as TOTAL_PROTEIN,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Family_member_suffered_from_Chronic_disease limit 1) as Family_member_suffered_from_Chronic_disease,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Chronic_Respiratory_diseases limit 1) as Chronic_Respiratory_diseases,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Other_Disease_text limit 1) as Other_Disease_text,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @ALLERGY_COMMENT limit 1) as ALLERGY_COMMENT,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Family_Member_Chronic_Diseases limit 1) as Family_Member_Chronic_Diseases,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @ketone limit 1) as ketone,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Other_clinical_diagnosis_non_coded limit 1) as Other_clinical_diagnosis_non_coded,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Hypertension_Stages limit 1) as Hypertension_Stages,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @BASOPHILS limit 1) as BASOPHILS,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @X_RAY_CHEST limit 1) as X_RAY_CHEST,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Renal_Failure_Stages limit 1) as Renal_Failure_Stages,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Other_Diabetes_Drug limit 1) as Other_Diabetes_Drug,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @ELECTROCARDIOGRAM_DIAGNOSIS limit 1) as ELECTROCARDIOGRAM_DIAGNOSIS,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @other_medical_findings limit 1) as other_medical_findings,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @ELECTROCARDIOGRAM_DIAGNOSIS_text limit 1) as ELECTROCARDIOGRAM_DIAGNOSIS_text,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Asthma_medications limit 1) as Asthma_medications,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Predicted_Peak_Flow limit 1) as Predicted_Peak_Flow,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Peak_flow_before_salbutamol limit 1) as Peak_flow_before_salbutamol,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Clinical_diagnosis_for_asthma limit 1) as Clinical_diagnosis_for_asthma,
	(select concept_name(value_coded,'en') from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Peak_flow_after_salbutamol limit 1) as Peak_flow_after_salbutamol,
	(select value_numeric from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @ECHOCARDIOGRAM_COMMENT limit 1) as ECHOCARDIOGRAM_COMMENT,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Home_Based_Care_Practionner_Phone_Number limit 1) as Home_Based_Care_Practionner_Phone_Number,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @OTHER_GENERAL_EXAM_FINDINGS limit 1) as OTHER_GENERAL_EXAM_FINDINGS,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @Scar_Location limit 1) as Scar_Location,
	(select value_text from obs O where O.encounter_id=enc.encounter_id and voided=0 and O.concept_id= @result_to_other_medical_findings limit 1) as result_to_other_medical_findings

		
    from encounter enc
		inner join form f on f.form_id=enc.form_id
	 where f.name in 
	(
		'NCD Diabetes: rendez-vous','NCD Diabetes: Medication List','NCD Diabetes: Insulin List'
		,'NCD Diabetes: Other Investigations','NCD Diabetes: EXAM LABORATORY TEST','NCD Diabetes: Diagnosis and Problems',
		'NCD DIABETES: Exit from Care Information','NCD Diabetes: Enrollment form'
	)

    ;